// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXk7cQtr3vJbSLWrSnP0tEgWeARxjsHM',
    appId: '1:993839647310:web:ca994f0942261b0449d11f',
    messagingSenderId: '993839647310',
    projectId: 'flutter-firebase-dersler-b8a62',
    authDomain: 'flutter-firebase-dersler-b8a62.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-b8a62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VKh30OjWeUNykPb_Xc5ZKCyKy3OWS24',
    appId: '1:993839647310:android:2e57d7deada3387a49d11f',
    messagingSenderId: '993839647310',
    projectId: 'flutter-firebase-dersler-b8a62',
    storageBucket: 'flutter-firebase-dersler-b8a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3wgaqIqBOeiH0ykgg8Ope_pXaC8iz9A',
    appId: '1:993839647310:ios:825048066380e7f749d11f',
    messagingSenderId: '993839647310',
    projectId: 'flutter-firebase-dersler-b8a62',
    storageBucket: 'flutter-firebase-dersler-b8a62.appspot.com',
    iosClientId: '993839647310-ha6ir9qbjuvidri7te0ubjtphir1gnj8.apps.googleusercontent.com',
    iosBundleId: 'com.ahmetkarabudak.flutter',
  );
}
